# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: cpp
cache: apt
compiler:
  - gcc

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    # - llvm-toolchain-precise-3.8
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    # - clang-3.8
    - clang

env: COMPILER=g++-4.9

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev -y

script: make
